const CardsContent = [{
    id: 1,
    img: "#",
    title: "Libro 1",
    description: "Libro CSS",
    price: "$3500",
    stock: 3,
},
    {id: 2,
    img: "#",
    title: "Combo 2",
    description: "Libro HTML + Libro CSS",
    price: "$5600",
    stock: 3,
    },
    {id: 3,
    img: "#",
    title: "Combo 3",
    description: "Libro JS + Libro ReactsJs",
    price: "$6800",
    stock: 3,
    },
    {id: 3,
      img: "#",
      title: "Combo 4",
      description: "Combo FrontEnd",
      price: "$12000",
      stock: 3,
    },
  ]

  export default CardsContent;